# Generated by Django X.X on YYYY-MM-DD
# Այս կոդը կուղղի public_profile_id-ները

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    CustomUser = apps.get_model('main', 'CustomUser') # Փոխարինեք 'main'-ը
    for row in CustomUser.objects.all():
        row.public_profile_id = uuid.uuid4()
        row.save(update_fields=['public_profile_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'), # Համոզվեք, որ այստեղ ձեր նախորդ միգրացիայի անունն է
    ]

    operations = [
        # 1. Ավելացնում ենք դաշտը՝ թույլ տալով այն լինել դատարկ
        migrations.AddField(
            model_name='customuser',
            name='public_profile_id',
            field=models.UUIDField(null=True, unique=True),
        ),
        # 2. Յուրաքանչյուր օգտատիրոջ համար գեներացնում ենք ունիկալ UUID
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        
        # 3. Դարձնում ենք դաշտը պարտադիր (ոչ դատարկ)
        migrations.AlterField(
            model_name='customuser',
            name='public_profile_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]