# Generated by Django 5.2.3 on 2025-06-25 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250625_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='public_profile_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Հանրային ID (QR)'),
        ),
    ]
